# Generated by Django 2.1.5 on 2022-05-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20220502_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.CharField(blank=True, choices=[('1', 'On Due'), ('2', 'Overdue'), ('3', 'Done')], default=1, max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', 'Stuck'), ('2', 'Working'), ('3', 'Done')], default=2, max_length=7),
        ),
    ]
